version: '3'

services:
  web:
    build: ./web
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis_cache:6379
    depends_on:
      - redis_cache
  redis_cache:
    image: 'redis:5-alpine'
